# Generated by Django 2.0.5 on 2019-01-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=60)),
                ('address_line2', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.IntegerField(choices=[(1, 'Capital'), (2, 'Punjab'), (3, 'Sindh'), (4, 'Balochistan'), (5, 'Kpk')], default=1)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('customer_type', models.IntegerField(choices=[(1, 'registered'), (2, 'Non_registered')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.Profile'),
        ),
    ]
